site_name: Rota Robin Docs
repo_url: https://github.com/Capp3/rota-round
docs_dir: docs
site_dir: site

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes

nav:
  - Overview: prd.md
  - Development: development.md
  - Architecture: architecture.md
  - Technical Decisions: technical.md
  - Backend: backend.md
  - Frontend: frontend.md
  - Security (CSRF/CORS): csrf-cors.md
  - Logging: logging.md
  - Status: status.md
